### ISSUE TITLE
[Question] glimmer_wordle for other GUI toolkits?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer_wordle#1]
Hey Andy,

I see you quickly created glimmer_wordle here for SWT.

I am wondering whether there are plans to make it available for other toolkits too; if it is
not too much work. So assumingly tk may be simple I suppose. But this here is really
meant as a question, not as a "you must make it available for all of glimmer" - time is
a finite resource.

(There may be one minor use case for the above question, e. g. for people who may
struggle with jruby/java, so an alternative is available. But again, this is really meant
as a question, not as an attempt to distribute more work load as-is. I think tetris
and snake already cover tons of potential use cases, so other users can chime in
and expand the glimmer suite.)

**Comment by AndyObtiva** [comment]
Initially, Glimmer Wordle was intentionally created as a Mac app only.

People will not struggle with running it on the Mac even if it needs Java/JRuby because the game is packaged as [a fully-self-contained downloadable Mac DMG file](https://github.com/AndyObtiva/glimmer_wordle#download) that includes Java/JRuby within. People don't have to install Java or JRuby manually. They just extract the Mac DMG file like they normally do with other Mac apps, and the game just works!

Otherwise, I will consider supporting on all other platforms and GUI toolkits, and will keep this issue open until Wordle is implemented in all other platforms and GUI toolkits.

**Comment by AndyObtiva** [comment]
I opened issues for each GUI Toolkit/Environment that can be used to implement Glimmer Wordle.

I am closing this issue as a result.

Thank you for reporting.
