### ISSUE TITLE
[Low priority suggestion] Wordle dictionaries: italian, swedish, spanish, german ... :D

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer_wordle#4]
Hey there Andy,

Wordle is again (!) in the news.

https://heyman.info/2022/feb/17/avoid-the-apple-app-store/

This time with a complaint about iOS and Apple. But anyway, while I was reading the news there,
I wondered whether glimmer_wordle has support for dictionaries (e. g. words in non-english
languages such as italian, swedish and so forth).

I am not suggesting that you provide these files as such, mind you - there are existing dictionaries out
there. For instance, german-to-english can use this file: https://www-user.tu-chemnitz.de/~fri/ding/
(see the screenshot in the middle; don't worry about the german text, it's just a dictionary
and a tk GUI built around it. Good thing is that people can download the translations so
they'd have tons of wordle-possible files.)

So this issue is more like requesting that glimmer_wordle allows loading data from a file
or a hash (and if a hash then perhaps grab a random element from there via some
general load-functionality or something, if that does not exist yet). Anyway, this is a very
low priority issue, so as always feel free to proceed with this issue in any way, shape or
form.

PS: Can glimmer_wordle be styled in a similar way as the two screenshots? E. g. with
user-defineable colours for the highlighted words or something like that. That keyboard
thing on the bottom is quite interesting, perhaps I should try to clone that via ruby-gtk3
one day. :D

**Comment by AndyObtiva** [comment]
> But anyway, while I was reading the news there,
> I wondered whether glimmer_wordle has support for dictionaries (e. g. words in non-english
> languages such as italian, swedish and so forth).
> 
> I am not suggesting that you provide these files as such, mind you - there are existing dictionaries out
> there. For instance, german-to-english can use this file: https://www-user.tu-chemnitz.de/~fri/ding/
> (see the screenshot in the middle; don't worry about the german text, it's just a dictionary
> and a tk GUI built around it. Good thing is that people can download the translations so
> they'd have tons of wordle-possible files.)

This is a good feature to support in the future.

Currently, Glimmer Wordle only has English words in two files under the [config](https://github.com/AndyObtiva/glimmer_wordle/tree/master/config) directory:
- [wordle-allowed-guesses.txt](https://github.com/AndyObtiva/glimmer_wordle/blob/master/config/wordle-allowed-guesses.txt)
-  [wordle-answers-alphabetical.txt](https://github.com/AndyObtiva/glimmer_wordle/blob/master/config/wordle-answers-alphabetical.txt)

I could not utilize dictionaries since the game requires 5-letter words only and translations in other languages are not guaranteed to be 5-letter words.

However, you are welcome to contribute 1 file per language, containing 5-letter words to be guesses for answers (no need to match the English 2-file format since that was just the original Wordle approach, but we can change it for other languages and have one file per language as that's much simpler).

Of course, I realize you probably don't speak all the languages you suggested. In that case, please submit languages that you can contribute, like German. I might be able to contribute French since it is one of my spoken languages.

We'll leave other languages to be contributed by other people. I am willing to support all western European and American-spoken languages only. Other languages have a cultural barrier that I'd rather not cross, and would rather leave to people from those other countries to handle.

Anyways, these are all the common Western and Northern Europe languages (not supporting uncommon ones for now, but let me know if I forgot any common ones) :
- Dutch
- English [IMPLEMENTED]
- French
- German
- Greek
- Italian
- Portugese
- Spanish
- Danish
- Finnish
- Norwegian
- Swedish

> So this issue is more like requesting that glimmer_wordle allows loading data from a file
> or a hash (and if a hash then perhaps grab a random element from there via some
> general load-functionality or something, if that does not exist yet). Anyway, this is a very
> low priority issue, so as always feel free to proceed with this issue in any way, shape or
> form.

This is not worth supporting if we are going to add all the languages mentioned above anyways. Besides, the code is open-source and anyone can fork it and add other language files or that specific file-arg/hash feature if needed.

> PS: Can glimmer_wordle be styled in a similar way as the two screenshots? E. g. with
> user-defineable colours for the highlighted words or something like that. That keyboard
> thing on the bottom is quite interesting, perhaps I should try to clone that via ruby-gtk3
> one day. :D

There is already a [TODO](https://github.com/AndyObtiva/glimmer_wordle/blob/master/TODO.md) item to update the colors to better match the original Wordle:

- Adjust the dark yellow (to #c9b458), dark green (to #6aaa64), and dark gray (to rgb 120 124 126) colors to match the original Wordle game colors

Otherwise, I do not want to suport color customization. It's just extra code for something unimportant. The game should just focus on the substance, not style! The substance is having good 5-letter word lists for good playability.

Thank you for reporting this issue.

I will likely open separate issues per language (German Support, French Support, Italian Support, etc...) and then close this issue once I am done with that and with updating the color scheme to better match the original Wordle.

Cheers!

**Comment by AndyObtiva** [comment]
> That keyboard
> thing on the bottom is quite interesting, perhaps I should try to clone that via ruby-gtk3
> one day. :D

I forgot to address that part of your comment.

That keyboard thing is not interesting at all. It is how the keyboard looks like on cell phones because cell phone reasons don't have a real keyboard. I already have that keyboard thing on top in my wordle screenshot:

![wordle screenshot](https://raw.githubusercontent.com/AndyObtiva/glimmer_wordle/master/screenshots/glimmer-wordle.png)

However, it is only there to display the letters that have been revealed as included at the right place (green), included at the wrong place (yellow), or not included (grey).

In fact, given that desktop users can use the real keyboard much faster, I will be rearranging the keyboard letters at the top to be in alphabetical order (instead of keyboard order) as that will better help users to quickly pinpoint if a letter is correct or not.

I already added that to the [TODO](https://github.com/AndyObtiva/glimmer_wordle/blob/master/TODO.md) list.

**Comment by AndyObtiva** [comment]
I updated the color scheme in [v1.1.0](https://rubygems.org/gems/glimmer_wordle/versions/1.1.0) to be just like the original Wordle.

Additionally, I created issues for every language that needs support (you are welcome to [contribute a 5-letter-word list in German](https://github.com/AndyObtiva/glimmer_wordle/issues/7) if you like).

Closing this issue as a result.
